module.exports.Queries = {
 GET_CUSTOMERS_QUERY:`SELECT FIRST_NAME, LAST_NAME, PHON_NUMBER, CUSTOMER_ID, EMAIL,COUNTRY.COUNTRY_NAME, CITY_NAME FROM ECOMMERCE.CUSTOMERS
                      JOIN ECOMMERCE.COUNTRY USING (COUNTRY_ID)  JOIN ECOMMERCE.CITY USING (CITY_ID);`,
 
 INSERT_CUSTOMER_QUERY:`INSERT INTO ecommerce.customers(first_name, last_name, phon_number, email, country_id, city_id)
                        VALUES($1, $2, $3, $4, 1, 1);`,
                        
 GET_PRODUCTS_QUERY: `SELECT PRODUCTI_ID, PRODUCT_NAME, UNIT, PRICE_PER_UNIT, CATEGORY_ID, CATEGORY_NAME, DESCRIPTION
                      FROM ECOMMERCE.PRODUCT JOIN ECOMMERCE.CATEGORY USING(CATEGORY_ID);`,

 INSERT_PRODUCT_QUERY: `INSERT INTO ECOMMERCE.PRODUCT (PRODUCT_NAME, UNIT, PRICE_PER_UNIT, DESCRIPTION, CATEGORY_ID)
                        VALUES($1, $2, $3, $4, 1);`,

 UPDATE_CUSTOMER_QUERY: `UPDATE ECOMMERCE.CUSTOMERS SET FIRST_NAME=$1, LAST_NAME=$2, PHON_NUMBER=$3
                         WHERE EMAIL=$4;`,                    
};
